site_name: skullcrushers
site_description: Reverse Engineering, Assembly, Systems Programming and Debugging Notes
site_url: https://skllcrshrs.github.io/notes-portal/

theme:
  name: material
  font: false
  palette:
    scheme: default
    primary: white
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search

nav:
  - RE:
      - Overview: re/index.md

  - RE4B:
      - Overview: re4b/index.md

  - CSAPP:
      - Overview: csapp/index.md

  - Modern x86:
      - Overview: modern-x86/index.md
      - Historical Overview: modern-x86/chapter-1-x86-64-core-architecture.md

  - PBA:
      - Overview: pba/index.md

  - Reversing:
      - Overview: reversing/index.md

  - Radare2:
      - Overview: radare2/index.md
